apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.peanutsNamespace }}
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigJSON }}

