secrets:
  password: ENC[AES256_GCM,data:pV8z4jfGpo8Y,iv:5wamnXENBD4QifzIYR+CY//4Ds3/Umo1/BrB1kQF01g=,tag:JNRe5NL2jpUi6INwxFSr8Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-02-23T12:06:22Z"
  mac: ENC[AES256_GCM,data:oK1DgLE6vn301bDRkwC8CYZpZ7bq2K2L84CsoRboqrfzhtHcU4EzrqCLN7p4HiyP9Xkfq1pgLL4LQCfQmGWU7i+/Vtt8t9WOrmORfrfGD+GlhCImZG0t4hrJiq91EQaDZH7oslwpUgxHXtrQUTNMNZ7zBogfQvP/2eKqWQyin3A=,iv:mEIp4fSXkLxMJsTARr4zEcwzUjcSJB+2P1uYF/pYNn8=,tag:6xBhHR7xUYTMeIE1Oth6zw==,type:str]
  pgp:
    - created_at: "2024-02-23T12:05:49Z"
      enc: |
        -----BEGIN PGP MESSAGE-----
        
        hQGMA415ZPgQcebyAQv9GGv8TqEVOUqogNAydmPTa7VPlSofmik5ft+TQLySuS7u
        VOGmeQFYDeQOw5wUgq3N5Vbj49RGqXIqdwRjKba1/WJ6/jZAoTEfAGm/jU6njx+z
        50JngJu75ERjsrieFGRjtwQpWKrV3DrIVdOWjh//D6UvcYMP6nWDYENJON/qq1qR
        k5tr6H8+U0se2TeGGpD2T3F+iTh9fNGAGFAdT1yFAiBPNiZKhowdLa7VBEC4xfzN
        KfDzu4ZGq8zuBLmIk4WWCEMt6Nvw9biJviIm/2z58URoiYEG+tLh7hUH8n40EBmG
        dtKPIFr9Vs4bOwQwj9UKN1zXzdHtMWVI8qcnI3Fo0XuaYFroTp662tc/chiYCI8n
        MazWtUW/P8zAskgpBhEXgZOYOYmr3jeV7KZhPoJnFLwWSxWa7yorALRiB5URw3vq
        hVuVWi3vFR1+WMs/UEc3L0BBr6YVwArmmtLJjn+gZ34PvdHLmr1GvTiRINSy8Jx9
        RsZptl6ypmA1nOsTVOuq0l4BKvdiEaH6CPZD03YL4392P1y3IJQwv/rL4TvZvLU5
        GpNxo7+H/33p+dC/9GGOFDAbhKSOUrkYo9tw9t2btEiDUWoQHTJsRyaq8Ruy7zXE
        eCTGFxXxy/MaKxwYD2HC
        =W1Ff
        -----END PGP MESSAGE-----
      fp: D5E7EB5743FD620565D7E2D3573B098F001BBE1D
  unencrypted_suffix: _unencrypted
  version: 3.7.3
