apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dbaas-dev@cloud.ionos.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
      - selector:
          dnsZones:
            - "ionos.com"
            - "tigerdb.de"
        dns01:
          webhook:
            groupName: dbaas-certs.ionos.com
            solverName: dns-endpoint-solver
            config: {}
