apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: ${keyid}
      keySecretRef:
        name: zerossl-hmac-key
        key: secret
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
      - http01:
          ingress:
            class: nginx
      - selector:
          dnsZones:
            - "ionos.com"
            - "tigerdb.de"
        dns01:
          webhook:
            groupName: dbaas-certs.ionos.com
            solverName: dns-endpoint-solver
            config: {}
