apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/shalabi67/KubernetesGitOps
        revision: main
        directories:
          - path: clusters/dbaas/locations/de-fra/cert-manager/*
  template:
    metadata:
      name: '{{ .Values.name }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/shalabi67/KubernetesGitOps
        targetRevision: main
        path: '{{ .Values.path }}'
      destination:
        server: https://kubernetes.default.svc  # TODO: we need to set actual k8s cluster
        namespace: cert-manager