apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: '{{ .Values.repoURL }}'
        revision: main
        directories:
          - path: '{{ .Values.repoURL }}/cert-manager/*'
  template:
    metadata:
      name: '{{ .Values.name }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: '{{ .Values.repoURL }}'
        targetRevision: main
        path: '{{ .Values.path }}'
      destination:
        server: '{{ .Values.cluster }}' # TODO: we need to set actual k8s cluster
        namespace: cert-manager