apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  generators:
    - git:
        repoURL: {{ .Values.repoURL }}
        revision: main3
        directories:
          - path: clusters/dbaas/locations/de-fra/cert-manager/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: dbaas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: main4
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc  # TODO: we need to set actual k8s cluster
        namespace: cert-manager