apiVersion: v2
name: prometheus-crds
description: A Helm chart for Kubernetes
dependencies:
  - name: prometheus-crds
    repository: oci://ghcr.io/ionos-cloud/dbaas-charts/helm
    version: v0.65.3

type: application
version: 0.1.0
appVersion: "1.16.0"
