repoURL: https://github.com/shalabi67/KubernetesGitOps
name: "{{path.basename}}"
path: "{{path}}"
cluster: "https://kubernetes.default.svc"
repoPath: "clusters/dbaas/locations/de-fra"
project: default
branch: main
argocdNamespace: argocd
namespaces:
  - cert-manager
  - dblet-system
  - default
  - monitoring
  - crossplane-system
  - ingress-nginx
  - velero
  - dbaas-kms


